apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-x5bv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-x5bv
    app.kubernetes.io/part-of: tkrw-pr712-0075-0015-app
  name: devfile-sample-x5bv0nax
spec:
  path: /
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-sample-x5bv
    weight: null
status: {}
